### ISSUE TITLE
Issue in learn errors

### ISSUE THREAD

**Issue by Jackfabo** [giovannellilab/dada2_pipeline#3]
when i try to make dada2 learn errors i get this message:

Error in learnErrors(filtFs1, multithread = TRUE, randomize = TRUE) : 
  could not find function "learnErrors"

what should i do to make learn errors work?

**Comment by dgiovannelli** [comment]
Did you load the Dada2 library using
`library(Dada2)`
upon restarting your jupyter session?

**Comment by Jackfabo** [comment]
yes i did that and now it work.
