### ISSUE TITLE
error in assign species silva

### ISSUE THREAD

**Issue by Jackfabo** [giovannellilab/dada2_pipeline#5]
i have run the folowing command line:
**taxa <- addSpecies(taxa, "~/Downloads/silva_nr_v138_train_set.fa.gz")**
and i get this error as a result:

> `Error in assignSpecies(seqs, refFasta = refFasta, allowMultiple = allowMultiple, : Incorrect reference file format for assignSpecies (this looks like a file formatted for assignTaxonomy).
> 
> Traceback:
> 1. addSpecies(taxa, "~/Downloads/silva_nr_v138_train_set.fa.gz")
> 2. assignSpecies(seqs, refFasta = refFasta, allowMultiple = allowMultiple, 
>  .     tryRC = tryRC, n = n, verbose = verbose)
> 3. stop("Incorrect reference file format for assignSpecies (this looks like a file formatted for assignTaxonomy).")`

i will attach a zip file with my jupyter notebook file
[Dada 2 Pipeline example.zip](https://github.com/giovannellilab/dada2_pipeline/files/4698052/Dada.2.Pipeline.example.zip)

**Comment by MatS792** [comment]
You are using the wrong file. If you check on the dada2_pipeline proposed and on the dada2 tutorial, you will find that silva_nr_v138_train_set.fa.gz is the file to assign **taxonomy** while the file called:  silva_species_assignment_v138.fa.gz is used to assign the **species**.
From: https://github.com/giovannellilab/dada2_pipeline/blob/master/dada2_pipeline.r
### taxa <- assignTaxonomy(seqtab.nochim, "~/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
### taxa <- addSpecies(taxa, "~/silva_species_assignment_v132.fa.gz")
In this case, it is used a previous version of SILVA.
