### ISSUE TITLE
sum(seqtab.nochim)/sum(seqtab) 

### ISSUE THREAD

**Issue by rosaria29** [giovannellilab/dada2_pipeline#6]
Ho fatto una serie di prove di taglio l 'ultima è quella che ritengo migliore ma resta il problema che dopo il comando sum(seqtab.nochim)/sum(seqtab) mi esce un valore basso

**Comment by MatS792** [comment]
Ok, I need you to paste here the forward and reverse quality plot, the last version of the filter and trim command you used, and the values of reads.in and reads out. you get with the command head(out).

**Comment by dgiovannelli** [comment]
Solved offline
